# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore **/*.csproj
    - name: Test
      run: dotnet test **/*.Test.csproj --verbosity normal
    - name: Build
      run: dotnet pack PolyhydraGames.Api.CDN.csproj --no-restore
    - name: push to NuGet
      uses: toolsniubility/push-nuget@main
